spring:
  profiles:
    default: debug

  jpa:
    hibernate:
      ddl-auto: create
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 100
    open-in-view: false