### 회원가입
POST http://localhost:8080/user/sign-up
Content-Type: application/json

{
  "email" : "test@naver.com",
  "password" : "Abcd1234!",
  "confirmPassword" : "Abcd1234!",
  "name" : "asdf",
  "birth" : "2023-09-19"
}

### 로그인
POST http://localhost:8080/user/sign-in
Content-Type: application/json

{
  "email" : "test",
  "password" : "Abcd1234!"
}

